name: First GitHub Action

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello Message
        run: echo "Hello! First GitHub Action run.."
